services:
  challenge-api:
    image: redteamsubnet61/rest-abs-challenge:6.0.1
    build:
      context: ./src/abs_challenge/challenge
    restart: unless-stopped
    platform: linux/amd64
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      ABS_CHALLENGE_API_PORT: ${ABS_CHALLENGE_API_PORT:-10001}
      ABS_API_PORT: ${ABS_API_PORT:-10001}
      ABS_API_CONFIGS_DIR: ${ABS_API_CONFIGS_DIR:-/etc/rest-abs-challenge}
      ABS_API_LOGS_DIR: ${ABS_API_LOGS_DIR:-/var/log/rest-abs-challenge}
      ABS_API_DATA_DIR: ${ABS_API_DATA_DIR:-/var/lib/rest-abs-challenge}
    env_file:
      - path: .env
        required: false
    volumes:
      - "./volumes/configs/rest-abs-challenge:${ABS_API_CONFIGS_DIR:-/etc/rest-abs-challenge}"
      - "./volumes/storage/rest-abs-challenge/logs:${ABS_API_LOGS_DIR:-/var/log/rest-abs-challenge}"
      - "./volumes/storage/rest-abs-challenge/data:${ABS_API_DATA_DIR:-/var/lib/rest-abs-challenge}"
    ports:
      - "${ABS_CHALLENGE_API_PORT:-10001}:${ABS_CHALLENGE_API_PORT:-10001}"
    tty: true
